Messages:
  NUMBER_EXCEPTIONS: "&cНедостаточно параметров!"
  CONSOLE_SENDER: "&cЭту команду может использовать только игрок!"
  NOT_FOUND_PARAMETRS: "&cНеизвестные параметры!"
  NOT_HAVE_PERMISSIONS: "&cНедостаточно прав!"
  