Config:
  Server: server
  MainWorld: world
  ScriptsPath: /home/scripts/
  Messages:
    - NumberException:::&cНедостаточно параметров!
    - ConsoleSender:::&cЭту команду может использовать только игрок!
    - NotFoundParametrs:::&cНеизвестные параметры!
    - HaventPermission:::&cНедостаточно прав!
MySQL:
  Host: localhost
  Port: 3306
  User: root
  Database: root
  Password: password